
#include <stdio.h>

void gen_header(FILE *fp)
{
  fprintf(fp, "<!--\n");
  fprintf(fp, "Auto generated file DO NOT EDIT\n");
  fprintf(fp, "Generated by: %s\n", __FILE__);
  fprintf(fp, "-->\n");

  fprintf(fp, "<svg xmlns=\"http://www.w3.org/2000/svg\"\n");
  fprintf(fp, "     xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n");
  fprintf(fp, "     width=\"100%%\" height=\"100%%\" viewBox=\"%d %d %d %d\" onload=\"load()\">\n",
          0, 0, 300, 150);
  fprintf(fp, "\n");
  fprintf(fp, "  <title>%s</title>\n", "panel light");
  fprintf(fp, "  <metadata>author: Don Carr</metadata>\n");
  fprintf(fp, "\n");
  fprintf(fp, "  <defs>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"grayRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"#fafafa\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"100%%\" stop-color=\"#808080\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"darkgrayRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"darkgrey\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"100%%\" stop-color=\"black\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"redRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"red\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"100%%\" stop-color=\"darkred\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"darkredRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"darkred\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"40%%\" stop-color=\"black\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"greenRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"lime\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"150%%\" stop-color=\"darkgreen\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"darkgreenRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"darkgreen\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"40%%\" stop-color=\"black\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"yellowRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"yellow\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"100%%\" stop-color=\"orange\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <radialGradient id=\"darkyellowRadial\" cx=\"50%%\" cy=\"50%%\" r=\"50%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"darkorange\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"100%%\" stop-color=\"black\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </radialGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "    <linearGradient id=\"grLinearV\" x1=\"0%%\" y1=\"0%%\" x2=\"100%%\" y2=\"0%%\" spreadMethod=\"pad\" gradientUnits=\"objectBoundingBox\">\n");
  fprintf(fp, "      <stop offset=\"0%%\" stop-color=\"#808080\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "      <stop offset=\"50%%\" stop-color=\"#fafafa\" stop-opacity=\"1\"/>\n");
  fprintf(fp, "    </linearGradient>\n");
  fprintf(fp, "\n");
  fprintf(fp, "  </defs>\n");
}
 
void gen_button(FILE *fp,double x, double y, double diameter, const char *radial)
{
  fprintf(fp, "<circle cx=\"%lf\" cy=\"%lf\" r=\"%lf\" stroke=\"black\" stroke-width=\"1\" fill=\"url(#%s)\"/>",
                            x, y, diameter / 2.0, radial);
}


int main(int argc, char *argv[])
{
  gen_header(stdout);
  gen_button(stdout, 30, 30, 20, "greenRadial");
  gen_button(stdout, 30, 60, 20, "darkgreenRadial");
  gen_button(stdout, 60, 30, 20, "redRadial");
  gen_button(stdout, 60, 60, 20, "darkredRadial");
  gen_button(stdout, 90, 30, 20, "grayRadial");
  gen_button(stdout, 90, 60, 20, "darkgrayRadial");
  gen_button(stdout, 30, 90, 20, "yellowRadial");
  gen_button(stdout, 60, 90, 20, "darkyellowRadial");
  fprintf(stdout, "\n");
  fprintf(stdout, "</svg>\n");
}
