

#define READ_OUTPUT_TABLE (0x01)
#define READ_INPUT_TABLE (0x02)
#define READ_REGISTERS (0x03)
#define READ_ANALOG_INPUTS (0x04)
#define FORCE_SINGLE_OUTPUT (0x05)
#define PRESET_SINGLE_REGISTER (0x06)
#define READ_EXCEPTION_STATUS (0x07)
#define LOOPBACK (0x08)
#define FORCE_MULTIPLE_OUTPUTS (0x0F)
#define PRESET_MULTIPLE_REGISTERS (0x10)
#define REPORT_DEVICE_TYPE (0x11)
#define READ_SCRATCH_PAD (67)

