#! /bin/sh

### BEGIN INIT INFO
# Provides:	        react2	
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:    React2	
### END INIT INFO

set -e


test -x /usr/local/bin/react2 || exit 0

chrooted() {
    # borrowed from udev's postinst
    # and then borrowed from initramfs-tools's preinst
    if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
	# the devicenumber/inode pair of / is the same as that of
	# /sbin/init's root, so we're *not* in a chroot and hence
	# return false.
	return 1
    fi
    return 0
}

# The init.d script is only for chroots
if [ -e /etc/init/react2.conf ] && ! chrooted; then
    exec /lib/init/upstart-job react2 "$@"
fi

umask 022

if test -f /usr/local/etc/react2/default/react2; then
    . /usr/local/etc/react2/default/react2
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    REACT2_OPTS="$REACT2_OPTS $2"
fi

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_no_start() {
    continue
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 1 || true
	fi
	if ! run_by_init; then
	    log_action_msg "/dev/null is not a character device!" || true
	fi
	exit 1
    fi
}

check_privsep_dir() {
    # Create the PrivSep empty dir if necessary
    if [ ! -d /var/run/react2]; then
	mkdir /var/run/react2
	chmod 0755 /var/run/react2
    fi
}

check_config() {
    continue
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/usr/local/bin"

case "$1" in
  start)
	check_privsep_dir
	check_for_no_start
	check_dev_null
	log_daemon_msg "Starting React2 daemon" "react2" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/react2.pid --exec /usr/local/bin/react2 -- $SSHD_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping React2 daemon" "react2" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/react2.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  reload|force-reload)
	check_for_no_start
	check_config
	log_daemon_msg "Reloading React2 daemon's configuration" "react2" || true
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/react2.pid --exec /usr/local/bin/react2; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	check_privsep_dir
	check_config
	log_daemon_msg "Restarting Reaact2 daemon" "react2" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/react2.pid
	check_for_no_start log_end_msg
	check_dev_null log_end_msg
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/react2.pid --exec /usr/local/bin/react2 -- $SSHD_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  try-restart)
	check_privsep_dir
	check_config
	log_daemon_msg "Restarting React2 daemon" "react2" || true
	RET=0
	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/react2.pid || RET="$?"
	case $RET in
	    0)
		# old daemon stopped
		check_for_no_start log_end_msg
		check_dev_null log_end_msg
		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/react2.pid --exec /usr/local/bin/react2 -- $SSHD_OPTS; then
		    log_end_msg 0 || true
		else
		    log_end_msg 1 || true
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)" || true
		log_end_msg 0 || true
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)" || true
		log_end_msg 1 || true
		;;
	esac
	;;

  status)
	status_of_proc -p /var/run/react2.pid /usr/local/bin/react2 react2 && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/react2 {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
