/***************************
This is an auto-generated file, do NOT edit!!
   generated by ../../gen_point/gen_one_obj
***************************/
#include <stdio.h>
#include <stdlib.h>
#include "rtcommon.h"
#include "arg.h"
#include "db_point.h"


/***************************/

ai_point_t *ai_point_t::create_one(int argc, char *argv[], char *err, int esz)
{
  ai_point_t *objp;
  objp = new ai_point_t;
  if (objp == NULL)
  {
    perror("new ai_point_t");
    return NULL;
  }
  safe_strcpy(objp->tag, (const char*) argv[0], sizeof(objp->tag));
  safe_strcpy(objp->description, (const char*) argv[1], sizeof(objp->description));
  safe_strcpy(objp->eu, (const char*) argv[2], sizeof(objp->eu));
  objp->driver = atoi(argv[3]);
  objp->card = atoi(argv[4]);
  objp->channel = atoi(argv[5]);
  objp->eu_lo = atof(argv[6]);
  objp->eu_hi = atof(argv[7]);
  objp->raw_lo = atof(argv[8]);
  objp->raw_hi = atof(argv[9]);
  objp->decimal_places = atoi(argv[10]);
  objp->zero_cutoff = atof(argv[11]);
  objp->lo_alarm = atof(argv[12]);
  objp->lo_caution = atof(argv[13]);
  objp->hi_caution = atof(argv[14]);
  objp->hi_alarm = atof(argv[15]);
  objp->deadband = atof(argv[16]);
  objp->lo_alarm_enable = (argv[17][0] == '1') ||
             (argv[17][0] == 'T') ||
             (argv[17][0] == 't');
  objp->lo_caution_enable = (argv[18][0] == '1') ||
             (argv[18][0] == 'T') ||
             (argv[18][0] == 't');
  objp->hi_caution_enable = (argv[19][0] == '1') ||
             (argv[19][0] == 'T') ||
             (argv[19][0] == 't');
  objp->hi_alarm_enable = (argv[20][0] == '1') ||
             (argv[20][0] == 'T') ||
             (argv[20][0] == 't');
  return objp;
}
