/***************************
This is an auto-generated file, do NOT edit!!
   generated by ../../gen_point/gen_one_obj
***************************/
#include <stdio.h>
#include <sqlite3.h>
#include "rtcommon.h"
#include "arg.h"
#include "gen_common.h"
int main(int argc, char *argv[])
{
  sqlite3 *sqdb;
  int retval;
  char *errmsg;

  printf("Creating 'react_def.db'\n");
  retval = sqlite3_open_v2("react_def.db",  &sqdb,
     SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL);
  if (retval != SQLITE_OK)
  {
    printf("Can not open db, error = %d\n", retval);
    printf("Err = %s\n", sqlite3_errmsg(sqdb));
    return 0;
  }
  else
  {
    printf("SUCCESS\n");
  }
  
  retval = sqlite3_exec(sqdb,
      "create table ai(tag VARCHAR(25), description VARCHAR(50), eu VARCHAR(12), driver INT, card INT, channel INT, eu_lo FLOAT, eu_hi FLOAT, raw_lo FLOAT, raw_hi FLOAT, decimal_places INT, zero_cutoff FLOAT, lo_alarm FLOAT, lo_caution FLOAT, hi_caution FLOAT, hi_alarm FLOAT, deadband FLOAT, lo_alarm_enable BOOLEAN, lo_caution_enable BOOLEAN, hi_caution_enable BOOLEAN, hi_alarm_enable BOOLEAN, PRIMARY KEY (tag));",
             NULL, NULL, &errmsg);
  if (retval != SQLITE_OK)
  {
    printf("query = create table ai(tag VARCHAR(25), description VARCHAR(50), eu VARCHAR(12), driver INT, card INT, channel INT, eu_lo FLOAT, eu_hi FLOAT, raw_lo FLOAT, raw_hi FLOAT, decimal_places INT, zero_cutoff FLOAT, lo_alarm FLOAT, lo_caution FLOAT, hi_caution FLOAT, hi_alarm FLOAT, deadband FLOAT, lo_alarm_enable BOOLEAN, lo_caution_enable BOOLEAN, hi_caution_enable BOOLEAN, hi_alarm_enable BOOLEAN, PRIMARY KEY (tag));\n");
    printf("Can not execute query, error = %d\n", retval);
    if (errmsg != NULL)
    {
      printf("errmsg: %s\n", errmsg);
      sqlite3_free(errmsg);
    }
    sqlite3_close(sqdb);
    return 0;
  }
  extern int write_one_ai(sqlite3 *sqdb, int argc, char *argv[]);
  insert_from_dat_file(sqdb, "./ai.dat", write_one_ai);
  sqlite3_close(sqdb);
}
