/***************************
This is an auto-generated file, do NOT edit!!
   generated by ../../gen_point/gen_one_obj
***************************/
#include <stdio.h>
#include <sqlite3.h>
#include "rtcommon.h"
#include "arg.h"


/***************************/

int write_one_ai(sqlite3 *sqdb, int argc, char *argv[])
{
  char qs[1000];  int retval;
  char *errmsg;
  if (argc < 21) // There must be at least 21 args
  {
    return -1;
  }
    snprintf(qs, sizeof(qs), "insert into \"ai\" values('%s','%s','%s',%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);",
          argv[0],
          argv[1],
          argv[2],
          argv[3],
          argv[4],
          argv[5],
          argv[6],
          argv[7],
          argv[8],
          argv[9],
          argv[10],
          argv[11],
          argv[12],
          argv[13],
          argv[14],
          argv[15],
          argv[16],
          ((argv[17][0] == 't') || (argv[17][0] == 'T') || (argv[17][0] == 'y') || (argv[17][0] == 'Y') || (argv[17][0] == '1')) ? "'T'" : "'F'",
          ((argv[18][0] == 't') || (argv[18][0] == 'T') || (argv[18][0] == 'y') || (argv[18][0] == 'Y') || (argv[18][0] == '1')) ? "'T'" : "'F'",
          ((argv[19][0] == 't') || (argv[19][0] == 'T') || (argv[19][0] == 'y') || (argv[19][0] == 'Y') || (argv[19][0] == '1')) ? "'T'" : "'F'",
          ((argv[20][0] == 't') || (argv[20][0] == 'T') || (argv[20][0] == 'y') || (argv[20][0] == 'Y') || (argv[20][0] == '1')) ? "'T'" : "'F'");
  printf("qs =%s\n", qs);
  retval = sqlite3_exec(sqdb, qs,
             NULL, NULL, &errmsg);
  if (retval != SQLITE_OK)
  {
    printf("qs = %s\n", qs);
    printf("Can not execute query, error = %d\n", retval);
    if (errmsg != NULL)
    {
      printf("errmsg: %s\n", errmsg);
      sqlite3_free(errmsg);
    }
    return -1;
  }
  return 0;
}
